#!/bin/bash
ulimit -s unlimited

cores=4
solver=mhdFoam # cEpotmhdEpotMultiRegionFoam
source ~/.openfoam_v2306_profile

blockMesh    2>&1 | tee log.blockMesh
decomposePar 2>&1 | tee log.decomposePar
if [[ ! $cores -eq 1 ]]
then
         
	/usr/bin/mpirun -np $cores $solver -parallel  2>&1 | tee log.$solver
else
	$solver 2>&1 | tee log.$solver
fi

reconstructPar    2>&1 | tee log.reconstruct
touch foam.foam
