#!/bin/bash
ulimit -s unlimited

cores=8  #4
solver=pimpleFoam # cEpotmhdEpotMultiRegionFoam
source ~/.openfoam_v2306_profile

if [[ ! $cores -eq 1 ]]
then
         
	/usr/bin/mpirun -np $cores $solver -parallel  2>&1 | tee log.$solver
else
	$solver 2>&1 | tee log.$solver
fi

touch foam.foam
