#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# settings

    # flag to enable computations in parallel mode
    parallel=true


#------------------------------------------------------------------------------

restore0Dir

if [ ! -d constant/polyMesh ]
then

    blockMesh  2>&1 | tee log.blockMesh  
 
    renumberMesh -overwrite -constant  2>&1 | tee log.renumberMesh

    checkMesh -allTopology -allGeometry -constant   2>&1 | tee log.checkMesh

fi

if [ "$parallel" = true ]
then

    decomposePar -cellDist 2>&1 | tee log.decomposePar

    ./runPimple              
    #runParallel $(getApplication)

    reconstructPar

else

    runApplication $(getApplication)

fi

runApplication postChannel


#------------------------------------------------------------------------------
